# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BinaryField()),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('data', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(default=25)),
                ('place', models.CharField(max_length=255)),
                ('available', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Course')),
            ],
        ),
        migrations.AddField(
            model_name='reg',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Section'),
        ),
        migrations.AddField(
            model_name='reg',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Client'),
        ),
    ]
