# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20170511_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
