# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_auto_20170512_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
