# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_auto_20170514_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='date',
            new_name='section_id',
        ),
        migrations.AddField(
            model_name='reg',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
