# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_remove_reg_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='sid',
        ),
        migrations.AddField(
            model_name='section',
            name='Students',
            field=models.ManyToManyField(to='section.Client'),
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
