# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0011_auto_20170520_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='Students',
        ),
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(to='section.Student'),
        ),
    ]
